import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // tutorialSidebar: [
  //   "شروع کار با سرویس فلش کال",
  //   {
  //     type: "category",
  //     label: "شروع سریع",
  //     items: ["/docs/FlashCall/create-service.mdx"],
  //   },
  // ],
};

export default sidebars;
